imports:
  - path: apis.jinja
  - path: cloud-function.jinja
  - path: pubsub-topic.jinja

resources:

  # APIs
  - name: enable-apis
    type: apis.jinja
    properties:
      apis:
        - cloudbuild.googleapis.com
        - cloudfunctions.googleapis.com
        - logging.googleapis.com
        - pubsub.googleapis.com
        - sqladmin.googleapis.com

  # Cloud SQL
  - name: services-instance  # This name will be unavailable for a week if you delete instance
    type: sqladmin.v1beta4.instance
    properties:
      databaseVersion: POSTGRES_14
      region: europe-central2
      zone: europe-central2-a
      settings:
        tier: db-f1-micro  # See `gcloud sql tiers list` for a full list
        dataDiskSizeGb: 10
        dataDiskType: PD_HDD
        storageAutoResize: false
        availabilityType: ZONAL
        backupConfiguration:
          enabled: false

  - name: services-db
    type: sqladmin.v1beta4.database
    properties:
      name: services-db
      instance: $(ref.services-instance.name)
      charset: utf8

  - name: services-user
    type: sqladmin.v1beta4.user
    metadata:
      dependsOn:
        - services-db
    properties:
      instance: $(ref.services-instance.name)
      name: services_user  # FIXME: Handle credentials
      password: services_password  # FIXME: Handle credentials
      host: "%"

  # Pub/Sub
  - name: pubsub-services-to-check
    type: pubsub-topic.jinja
    properties:
      name: services-to-check

  # Cloud functions
  - name: func-MonitorSpecificService
    type: cloud-function.jinja
    metadata:
      dependsOn:
        - services-instance
        - services-user
    properties:
      function: MonitorSpecificService
      region: europe-central2
      repo: alerting-platform
      repoPath: MonitorSpecificService
      inputTopic: $(ref.pubsub-services-to-check.topicName)
      environmentVariables:
        DB_CONN_NAME: $(ref.services-instance.connectionName)
        DB_USERNAME: services_user  # FIXME: Handle credentials
        DB_PASSWORD: services_password  # FIXME: Handle credentials
        DB_DATABASE: services-db  # FIXME: Handle credentials
        REQUEST_TIMEOUT_SEC: "3"
        ALERTING_WINDOW_SEC: "10"

  - name: func-WorkInProgress
    type: cloud-function.jinja
    metadata:
      dependsOn:
        - services-instance
        - services-user
    properties:
      function: WorkInProgress
      region: europe-central2
      repo: alerting-platform
      repoPath: WorkInProgress
      ingressSettings: ALLOW_ALL
      httpsSecurityLevel: SECURE_ALWAYS
      environmentVariables:
        DB_CONN_NAME: $(ref.services-instance.connectionName)
        DB_USERNAME: services_user  # FIXME: Handle credentials
        DB_PASSWORD: services_password  # FIXME: Handle credentials
        DB_DATABASE: services-db  # FIXME: Handle credentials